# Generated by Django 4.2.23 on 2025-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="braintree_id",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
